# Generated by Django 4.2.6 on 2023-10-27 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bucket',
            field=models.IntegerField(choices=[(1, 1), (2, 3), (3, 7), (4, 16), (5, 30)], default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_review_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 11, 43, 32, 649599, tzinfo=datetime.timezone.utc)),
        ),
    ]
