# Generated by Django 4.2.6 on 2023-10-27 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_bucket_alter_card_next_review_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bucket',
            field=models.IntegerField(choices=[(1, '1 Day'), (2, '3 Days'), (3, '7 Days'), (4, '16 Days'), (5, '30 Days')], default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_review_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 11, 54, 15, 115604, tzinfo=datetime.timezone.utc)),
        ),
    ]
